### ISSUE TITLE
python DownloadData showing error

### ISSUE THREAD

**Issue by Akshit052** [Aftaab99/OfflineSignatureVerification#33] opened 2022-08-28 06:25 UTC
zipfile.BadZipFile: File is not a zip file
It is showing this error and when i checked the zip locally it is showing unknown format or damaged.

**Comment by Aftaab99** [comment] 2024-02-18 17:48
Fixed now, closing as its a duplicate of #38.
Thank you for reporting.

**Closed as completed by Aftaab99** 2024-02-18 17:48 UTC
