### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by RizwanShaukat936** [Aftaab99/OfflineSignatureVerification#10] opened 2020-11-10 09:20 UTC
hi, i am trying to run this project I am facing these errors,
**1st dataset is not getting downloaded** 
"  raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1w2DEYX2pBhBNS2l4sqrl8j-Am4cNSBoZ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CC6940D0A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
"
**2nd i tried to run this project , i found server error**.
" Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." 

Please tell me how to resolve this issue, 
I couldn't run the project at all.
Thank you in advance

**Comment by Aftaab99** [comment] 2020-12-09 13:51
I just deleted both the model and dataset folders and tried running the DownloadData script again, it worked just fine. [StackOverflow says](https://stackoverflow.com/questions/15820739/python-urlerror-urlopen-error-errno-10060) the cause of this is likely your internet connection(the download size is about 250MB combined. Try lowering the chunk size in `DownloadData.py` if you have a slower connection).

You wouldnt be able to run the project without the model. The DownloadData script also downloads the pretrained model. Hence the second error.

Closing the issue. Feel free to reopen if required. 

Thanks for reporting!

**Closed as completed by Aftaab99** 2020-12-09 13:51 UTC
